#if !canImport(ObjectiveC)
import XCTest

extension CombinedDateTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CombinedDateTests = [
        ("testCompareDate", testCompareDate),
        ("testIncompleteDate", testIncompleteDate),
        ("testReleaseDate", testReleaseDate),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CombinedDateTests.__allTests__CombinedDateTests),
    ]
}
#endif
